version: "3.7"

services:
  webserver:
    image: ghcr.io/jensjeflensje/image-to-skin-frontend:production
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8083:80"
    depends_on:
      - backend
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: image_to_skin
      POSTGRES_PASSWORD: image_to_skin
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    command: gunicorn --bind=0.0.0.0:8000 image_to_skin.wsgi:application
    image: ghcr.io/jensjeflensje/image-to-skin-backend:production
    env_file:
      - .env
    depends_on:
      - database
      - redis
  backend_worker:
    command: python3 manage.py qcluster
    image: ghcr.io/jensjeflensje/image-to-skin-backend:production
    env_file:
      - .env
    volumes:
      - ./secrets/google-service-account.json:/app/google-service-account.json
    depends_on:
      - database
      - redis
  redis:
    image: redis:latest

volumes:
  postgres-data:
